services:
  - type: web
    name: chico-grill-delivery
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: USE_MEMORY
        value: "true"
